In [1]:
#imports
import pandas as pd

In [2]:
#Load the csv file for green taxis into a pandas dataframe
greenAug = pd.read_csv('green_tripdata_2013-08 (1).csv')
df_greenAug = pd.DataFrame(greenAug)

In [3]:
df_greenAug

                                  VendorID lpep_pickup_datetime  \
2 2013-08-01 08:14:37  2013-08-01 09:09:06                    N
  2013-08-01 09:13:00  2013-08-01 11:38:00                    N
  2013-08-01 09:48:00  2013-08-01 09:49:00                    N
  2013-08-01 10:38:35  2013-08-01 10:38:51                    N
  2013-08-01 11:51:45  2013-08-01 12:03:52                    N
  2013-08-01 14:33:39  2013-08-01 15:49:00                    N
  2013-08-01 17:19:00  2013-08-01 17:19:00                    N
  2013-08-01 17:22:00  2013-08-01 17:22:00                    N
  2013-08-01 17:24:00  2013-08-01 17:25:00                    N
  2013-08-01 19:21:09  2013-08-01 19:22:30                    N
  2013-08-01 19:29:27  2013-08-01 19:32:38                    N
  2013-08-01 19:33:28  2013-08-01 19:35:21                    N
  2013-08-02 09:37:44  2013-08-02 09:38:08                    N
  2013-08-02 09:43:58  2013-08-02 09:44:13                    N
  2013-08-02 09:44:43  2013-08-02 09:45:15                    N
  2013-08-02 11:26:32  2013-08-02 11:26:54                    N
  2013-08-02 11:32:36  2013-08-02 11:45:45                    N
  2013-08-02 11:46:27  2013-08-02 11:47:32                    N
  2013-08-02 12:10:46  2013-08-02 12:11:45                    N
  2013-08-02 12:19:55  2013-08-02 12:20:11                    N
  2013-08-02 12:30:00  2013-08-02 18:08:00                    N
  2013-08-02 12:51:01  2013-08-02 17:04:32                    N
  2013-08-02 18:00:50  2013-08-02 18:01:55                    N
  2013-08-02 18:04:20  2013-08-03 16:57:31                    N
  2013-08-02 18:05:15  2013-08-03 09:32:19                    N
  2013-08-03 17:22:42  2013-08-03 17:23:13                    N
  2013-08-05 09:01:22  2013-08-05 14:02:41                    N
  2013-08-05 10:16:04  2013-08-05 11:03:13                    N
  2013-08-05 11:05:58  2013-08-05 11:07:45                    N
  2013-08-05 11:14:37  2013-08-05 11:15:05                    N
...                                    ...                  ...
1 2013-08-31 23:23:38  2013-08-31 23:36:16                    N
2 2013-08-31 23:23:45  2013-08-31 23:34:26                    N
  2013-08-31 23:23:49  2013-08-31 23:31:26                    N
  2013-08-31 23:24:42  2013-08-31 23:50:50                    N
  2013-08-31 23:25:05  2013-08-31 23:35:31                    N
  2013-08-31 23:27:26  2013-08-31 23:54:49                    N
  2013-08-31 23:27:46  2013-08-31 23:41:39                    N
  2013-08-31 23:28:21  2013-09-01 00:00:58                    N
  2013-08-31 23:30:53  2013-08-31 23:54:56                    N
  2013-08-31 23:33:19  2013-08-31 23:38:51                    N
  2013-08-31 23:34:00  2013-08-31 23:43:00                    N
  2013-08-31 23:34:55  2013-08-31 23:51:43                    N
  2013-08-31 23:34:58  2013-08-31 23:50:56                    N
  2013-08-31 23:35:21  2013-08-31 23:48:13                    N
  2013-08-31 23:40:04  2013-08-31 23:41:42                    N
  2013-08-31 23:41:33  2013-09-01 00:00:18                    N
  2013-08-31 23:44:17  2013-08-31 23:52:01                    N
1 2013-08-31 23:45:43  2013-08-31 23:50:19                    N
2 2013-08-31 23:46:58  2013-08-31 23:51:07                    N
  2013-08-31 23:48:10  2013-09-01 00:09:26                    N
  2013-08-31 23:48:29  2013-08-31 23:59:44                    N
  2013-08-31 23:50:37  2013-09-01 00:01:12                    N
  2013-08-31 23:51:16  2013-08-31 23:58:45                    N
  2013-08-31 23:52:57  2013-08-31 23:58:45                    N
  2013-08-31 23:54:00  2013-08-31 00:06:00                    N
  2013-08-31 23:54:50  2013-08-31 23:57:30                    N
  2013-08-31 23:57:33  2013-09-01 00:10:03                    N
  2013-08-31 23:58:18  2013-09-01 00:25:07                    N
  2013-08-31 23:58:58  2013-09-01 00:06:31                    N
1 2013-08-31 23:59:14  2013-09-01 00:07:40                    N

                       Lpep_dropoff_datetime  Store_and_fwd_flag  RateCodeID  \
2 2013-08-01 08:14:37                      1            0.000000    0.000000
  2013-08-01 09:13:00                      1            0.000000    0.000000
  2013-08-01 09:48:00                      5            0.000000    0.000000
  2013-08-01 10:38:35                      1            0.000000    0.000000
  2013-08-01 11:51:45                      1            0.000000    0.000000
  2013-08-01 14:33:39                      1            0.000000    0.000000
  2013-08-01 17:19:00                      1            0.000000    0.000000
  2013-08-01 17:22:00                      1          -73.937767   40.758480
  2013-08-01 17:24:00                      1          -73.937927   40.757843
  2013-08-01 19:21:09                      1            0.000000    0.000000
  2013-08-01 19:29:27                      4            0.000000    0.000000
  2013-08-01 19:33:28                      1            0.000000    0.000000
  2013-08-02 09:37:44                      1            0.000000    0.000000
  2013-08-02 09:43:58                      1            0.000000    0.000000
  2013-08-02 09:44:43                      1            0.000000    0.000000
  2013-08-02 11:26:32                      1            0.000000    0.000000
  2013-08-02 11:32:36                      1            0.000000    0.000000
  2013-08-02 11:46:27                      1            0.000000    0.000000
  2013-08-02 12:10:46                      1            0.000000    0.000000
  2013-08-02 12:19:55                      1            0.000000    0.000000
  2013-08-02 12:30:00                      1            0.000000    0.000000
  2013-08-02 12:51:01                      1            0.000000    0.000000
  2013-08-02 18:00:50                      1            0.000000    0.000000
  2013-08-02 18:04:20                      1            0.000000    0.000000
  2013-08-02 18:05:15                      1            0.000000    0.000000
  2013-08-03 17:22:42                      1            0.000000    0.000000
  2013-08-05 09:01:22                      1            0.000000    0.000000
  2013-08-05 10:16:04                      1            0.000000    0.000000
  2013-08-05 11:05:58                      1            0.000000    0.000000
  2013-08-05 11:14:37                      1            0.000000    0.000000
...                                      ...                 ...         ...
1 2013-08-31 23:23:38                      1          -73.913605   40.765427
2 2013-08-31 23:23:45                      1          -73.950272   40.680496
  2013-08-31 23:23:49                      1          -73.844254   40.721390
  2013-08-31 23:24:42                      1          -73.846169   40.754543
  2013-08-31 23:25:05                      1          -73.861031   40.893051
  2013-08-31 23:27:26                      1          -73.844818   40.754986
  2013-08-31 23:27:46                      1          -73.954086   40.742813
  2013-08-31 23:28:21                      1          -73.846001   40.754578
  2013-08-31 23:30:53                      1          -73.849991   40.753479
  2013-08-31 23:33:19                      1          -73.829971   40.713734
  2013-08-31 23:34:00                      1          -73.845917   40.754639
  2013-08-31 23:34:55                      1          -73.967758   40.693268
  2013-08-31 23:34:58                      1          -73.991852   40.702530
  2013-08-31 23:35:21                      1          -73.833656   40.771580
  2013-08-31 23:40:04                      1          -73.926193   40.761082
  2013-08-31 23:41:33                      1          -73.921158   40.743267
  2013-08-31 23:44:17                      1          -73.946342   40.711445
1 2013-08-31 23:45:43                      1          -73.979172   40.678406
2 2013-08-31 23:46:58                      1          -73.943985   40.784100
  2013-08-31 23:48:10                      1          -73.924644   40.756287
  2013-08-31 23:48:29                      1          -73.920647   40.767956
  2013-08-31 23:50:37                      1          -73.941200   40.805779
  2013-08-31 23:51:16                      1          -73.844307   40.721352
  2013-08-31 23:52:57                      1          -73.917976   40.765259
  2013-08-31 23:54:00                      1          -73.845985   40.754650
  2013-08-31 23:54:50                      1          -73.943115   40.785336
  2013-08-31 23:57:33                      1          -73.824432   40.734287
  2013-08-31 23:58:18                      1          -73.964668   40.681309
  2013-08-31 23:58:58                      1          -73.932343   40.796421
1 2013-08-31 23:59:14                      1          -73.980034   40.676315

                       Pickup_longitude  Pickup_latitude  Dropoff_longitude  \
2 2013-08-01 08:14:37          0.000000         0.000000                  1
  2013-08-01 09:13:00          0.000000         0.000000                  2
  2013-08-01 09:48:00          0.000000         0.000000                  1
  2013-08-01 10:38:35          0.000000         0.000000                  1
  2013-08-01 11:51:45          0.000000         0.000000                  1
  2013-08-01 14:33:39          0.000000         0.000000                  1
  2013-08-01 17:19:00          0.000000         0.000000                  1
  2013-08-01 17:22:00        -73.937767        40.758480                  1
  2013-08-01 17:24:00        -73.937927        40.757843                  1
  2013-08-01 19:21:09          0.000000         0.000000                  5
  2013-08-01 19:29:27          0.000000         0.000000                  5
  2013-08-01 19:33:28          0.000000         0.000000                  5
  2013-08-02 09:37:44          0.000000         0.000000                  1
  2013-08-02 09:43:58          0.000000         0.000000                  1
  2013-08-02 09:44:43          0.000000         0.000000                  1
  2013-08-02 11:26:32          0.000000         0.000000                  1
  2013-08-02 11:32:36          0.000000         0.000000                  1
  2013-08-02 11:46:27          0.000000         0.000000                  1
  2013-08-02 12:10:46          0.000000         0.000000                  1
  2013-08-02 12:19:55          0.000000         0.000000                  1
  2013-08-02 12:30:00          0.000000         0.000000                  2
  2013-08-02 12:51:01          0.000000         0.000000                  1
  2013-08-02 18:00:50          0.000000         0.000000                  3
  2013-08-02 18:04:20          0.000000         0.000000                  2
  2013-08-02 18:05:15          0.000000         0.000000                  4
  2013-08-03 17:22:42          0.000000         0.000000                  1
  2013-08-05 09:01:22          0.000000         0.000000                  1
  2013-08-05 10:16:04          0.000000         0.000000                  3
  2013-08-05 11:05:58          0.000000         0.000000                  4
  2013-08-05 11:14:37          0.000000         0.000000                  2
...                                 ...              ...                ...
1 2013-08-31 23:23:38        -73.918091        40.741680                  1
2 2013-08-31 23:23:45        -73.934990        40.702396                  1
  2013-08-31 23:23:49        -73.818474        40.734043                  1
  2013-08-31 23:24:42        -73.965820        40.677544                  2
  2013-08-31 23:25:05        -73.901611        40.876530                  1
  2013-08-31 23:27:26        -73.969231        40.761219                  2
  2013-08-31 23:27:46        -74.000793        40.736462                  1
  2013-08-31 23:28:21        -73.974899        40.759235                  1
  2013-08-31 23:30:53        -73.977623        40.779022                  1
  2013-08-31 23:33:19        -73.824730        40.705601                  2
  2013-08-31 23:34:00        -73.860458        40.739819                  1
  2013-08-31 23:34:55        -73.989105        40.720303                  3
  2013-08-31 23:34:58        -74.007256        40.733669                  1
  2013-08-31 23:35:21        -73.843651        40.689556                  1
  2013-08-31 23:40:04        -73.928421        40.756069                  1
  2013-08-31 23:41:33        -73.902840        40.701447                  2
  2013-08-31 23:44:17        -73.951027        40.724358                  1
1 2013-08-31 23:45:43        -73.988785        40.670506                  1
2 2013-08-31 23:46:58        -73.952507        40.773121                  3
  2013-08-31 23:48:10        -73.984779        40.710838                  1
  2013-08-31 23:48:29        -73.885201        40.755516                  5
  2013-08-31 23:50:37        -73.967400        40.801105                  5
  2013-08-31 23:51:16        -73.827965        40.710865                  1
  2013-08-31 23:52:57        -73.922600        40.755390                  1
  2013-08-31 23:54:00        -73.884468        40.737869                  1
  2013-08-31 23:54:50        -73.932846        40.796619                  1
  2013-08-31 23:57:33        -73.850494        40.722317                  1
  2013-08-31 23:58:18        -74.000633        40.732147                  2
  2013-08-31 23:58:58        -73.955841        40.804691                  2
1 2013-08-31 23:59:14        -73.964218        40.652081                  1

                       Dropoff_latitude  Passenger_count  Trip_distance  \
2 2013-08-01 08:14:37              0.00            21.25            0.0
  2013-08-01 09:13:00              0.00            74.50            0.0
  2013-08-01 09:48:00              0.00             1.00            0.1
  2013-08-01 10:38:35              0.00             3.25            0.0
  2013-08-01 11:51:45              0.00             8.50            0.0
  2013-08-01 14:33:39              0.00             9.00            0.0
  2013-08-01 17:19:00              0.00             2.50            1.0
  2013-08-01 17:22:00              0.00             2.50            1.0
  2013-08-01 17:24:00              0.00             2.50            1.0
  2013-08-01 19:21:09              0.00             3.00            1.0
  2013-08-01 19:29:27              0.00             3.00            1.0
  2013-08-01 19:33:28              0.00             3.00            1.0
  2013-08-02 09:37:44              0.00             1.50            0.0
  2013-08-02 09:43:58              0.00             1.50            0.0
  2013-08-02 09:44:43              0.00             1.50            0.0
  2013-08-02 11:26:32              0.00             1.50            0.0
  2013-08-02 11:32:36              0.00             7.45            0.0
  2013-08-02 11:46:27              0.00             3.00            0.0
  2013-08-02 12:10:46              0.00             3.45            0.0
  2013-08-02 12:19:55              0.00             3.25            0.0
  2013-08-02 12:30:00              0.00           171.50            0.0
  2013-08-02 12:51:01              0.00            26.80            0.0
  2013-08-02 18:00:50              0.00             6.00            0.0
  2013-08-02 18:04:20              0.00          3569.00            1.0
  2013-08-02 18:05:15              0.00             2.50            1.0
  2013-08-03 17:22:42              0.00             3.25            0.0
  2013-08-05 09:01:22              0.00            31.60            0.0
  2013-08-05 10:16:04             26.47             7.50            0.0
  2013-08-05 11:05:58              0.00             2.50            0.0
  2013-08-05 11:14:37              0.00             3.00            0.0
...                                 ...              ...            ...
1 2013-08-31 23:23:38              2.20            11.00            0.5
2 2013-08-31 23:23:45              2.43            10.50            0.5
  2013-08-31 23:23:49              2.22             9.00            0.5
  2013-08-31 23:24:42             13.70            39.00            0.5
  2013-08-31 23:25:05              4.01            14.00            0.5
  2013-08-31 23:27:26              7.49            26.00            0.5
  2013-08-31 23:27:46              3.77            13.50            0.5
  2013-08-31 23:28:21             11.66            38.50            0.5
  2013-08-31 23:30:53             11.77            34.00            0.5
  2013-08-31 23:33:19              0.72             5.50            0.5
  2013-08-31 23:34:00              2.03             8.50            0.5
  2013-08-31 23:34:55              3.30            14.50            0.5
  2013-08-31 23:34:58              3.59            14.50            0.5
  2013-08-31 23:35:21              7.64            22.50            0.5
  2013-08-31 23:40:04              0.40             3.50            0.5
  2013-08-31 23:41:33              4.80            17.00            0.5
  2013-08-31 23:44:17              1.48             7.50            0.5
1 2013-08-31 23:45:43              0.80             5.50            0.5
2 2013-08-31 23:46:58              1.32             6.00            0.5
  2013-08-31 23:48:10              7.76            25.00            0.5
  2013-08-31 23:48:29              2.86            11.50            0.5
  2013-08-31 23:50:37              2.08             9.50            0.5
  2013-08-31 23:51:16              1.82             8.00            0.5
  2013-08-31 23:52:57              1.13             6.00            0.5
  2013-08-31 23:54:00              4.29            15.00            0.5
  2013-08-31 23:54:50              1.05             5.00            0.5
  2013-08-31 23:57:33              2.64            11.50            0.5
  2013-08-31 23:58:18              7.22            25.50            0.5
  2013-08-31 23:58:58              1.47             7.50            0.5
1 2013-08-31 23:59:14              2.20             9.00            0.5

                       Fare_amount  Extra  MTA_tax  Tip_amount  Tolls_amount  \
2 2013-08-01 08:14:37         0.00   0.00     0.00         NaN         21.25
  2013-08-01 09:13:00         0.50   0.00     0.00         NaN         75.00
  2013-08-01 09:48:00         0.00   0.00     1.00         NaN          2.10
  2013-08-01 10:38:35         0.00   0.00     0.00         NaN          3.25
  2013-08-01 11:51:45         0.50   0.00     0.00         NaN          9.00
  2013-08-01 14:33:39         0.50   0.00     0.00         NaN          9.50
  2013-08-01 17:19:00         0.50   0.00     0.00         NaN          4.00
  2013-08-01 17:22:00         0.50   0.00     5.33         NaN          9.33
  2013-08-01 17:24:00         0.50   0.00     1.11         NaN          5.11
  2013-08-01 19:21:09         0.50   0.00     0.00         NaN          4.50
  2013-08-01 19:29:27         0.50   0.00     0.00         NaN          4.50
  2013-08-01 19:33:28         0.50   0.08     0.00         NaN          4.58
  2013-08-02 09:37:44         0.50   0.00     0.00         NaN          2.00
  2013-08-02 09:43:58         0.50   0.00     0.00         NaN          2.00
  2013-08-02 09:44:43         0.50   0.00     0.00         NaN          2.00
  2013-08-02 11:26:32         0.50   0.00     0.00         NaN         11.00
  2013-08-02 11:32:36         0.00   0.00     0.00         NaN          7.45
  2013-08-02 11:46:27         0.50   0.00     0.00         NaN          3.50
  2013-08-02 12:10:46         0.00   0.00     0.00         NaN          3.45
  2013-08-02 12:19:55         0.00   0.00     0.00         NaN          3.25
  2013-08-02 12:30:00         0.50   0.00     0.00         NaN        172.00
  2013-08-02 12:51:01         0.50   0.00     0.00         NaN         27.30
  2013-08-02 18:00:50         0.50   0.00     0.00         NaN          6.50
  2013-08-02 18:04:20         0.50   0.00     0.00         NaN       3570.50
  2013-08-02 18:05:15         0.50   0.00     0.00         NaN          4.00

In [5]:
#drop rows without location data
df_greenAug = df_greenAug[df_greenAug.Pickup_longitude != 0]
#drop useless columns
df_greenAug.drop(df_greenAug.columns[[0,1,2,3,4,9,11,12,13,14,15,16,17,18,19]],axis = 1,inplace = True)

IndexError: index 9 is out of bounds for axis 1 with size 5

In [6]:
df_greenAug

                       Pickup_longitude  Pickup_latitude  Dropoff_longitude  \
2 2013-08-01 17:22:00        -73.937767        40.758480                  1
  2013-08-01 17:24:00        -73.937927        40.757843                  1
  2013-08-05 11:31:47       -115.179337        36.136684                  1
  2013-08-05 11:31:47       -115.179337        36.136684                  1
  2013-08-05 11:51:21       -115.179199        36.137009                  1
  2013-08-05 11:53:27       -115.179276        36.136826                  1
  2013-08-06 06:51:19        -73.937721        40.758369                  1
  2013-08-06 10:33:07        -76.979713        38.927326                  1
  2013-08-06 13:26:34        -73.937790        40.758358                  1
  2013-08-06 13:27:53        -73.937775        40.758450                  1
  2013-08-06 13:29:17        -73.937759        40.758389                  1
  2013-08-06 13:30:55        -73.937790        40.758350                  1
  2013-08-07 10:22:30        -76.979591        38.927288                  1
  2013-08-07 10:24:53        -76.979889        38.927174                  1
  2013-08-07 10:24:53        -76.979813        38.927128                  1
  2013-08-07 10:33:23        -76.979561        38.927151                  2
  2013-08-07 14:12:46        -73.937485        40.758209                  1
  2013-08-07 15:13:35       -115.179283        36.137066                  1
  2013-08-07 15:38:07        -73.937485        40.758137                  2
  2013-08-07 15:42:29        -73.937424        40.758152                  1
  2013-08-07 15:46:09        -73.937508        40.758251                  3
  2013-08-07 15:49:16        -73.937447        40.758183                  2
  2013-08-07 16:06:29        -73.937469        40.758202                  5
  2013-08-07 16:15:27        -73.937431        40.758213                  5
  2013-08-07 16:15:27        -73.937424        40.758251                  5
  2013-08-07 16:27:31        -73.937492        40.758194                  5
  2013-08-07 16:27:31        -73.937325        40.758198                  5
  2013-08-07 16:38:29        -73.937416        40.758087                  5
  2013-08-07 16:38:29        -73.937241        40.758106                  5
  2013-08-07 16:43:27        -73.937729        40.758305                  1
...                                 ...              ...                ...
1 2013-08-31 23:23:38        -73.918091        40.741680                  1
2 2013-08-31 23:23:45        -73.934990        40.702396                  1
  2013-08-31 23:23:49        -73.818474        40.734043                  1
  2013-08-31 23:24:42        -73.965820        40.677544                  2
  2013-08-31 23:25:05        -73.901611        40.876530                  1
  2013-08-31 23:27:26        -73.969231        40.761219                  2
  2013-08-31 23:27:46        -74.000793        40.736462                  1
  2013-08-31 23:28:21        -73.974899        40.759235                  1
  2013-08-31 23:30:53        -73.977623        40.779022                  1
  2013-08-31 23:33:19        -73.824730        40.705601                  2
  2013-08-31 23:34:00        -73.860458        40.739819                  1
  2013-08-31 23:34:55        -73.989105        40.720303                  3
  2013-08-31 23:34:58        -74.007256        40.733669                  1
  2013-08-31 23:35:21        -73.843651        40.689556                  1
  2013-08-31 23:40:04        -73.928421        40.756069                  1
  2013-08-31 23:41:33        -73.902840        40.701447                  2
  2013-08-31 23:44:17        -73.951027        40.724358                  1
1 2013-08-31 23:45:43        -73.988785        40.670506                  1
2 2013-08-31 23:46:58        -73.952507        40.773121                  3
  2013-08-31 23:48:10        -73.984779        40.710838                  1
  2013-08-31 23:48:29        -73.885201        40.755516                  5
  2013-08-31 23:50:37        -73.967400        40.801105                  5
  2013-08-31 23:51:16        -73.827965        40.710865                  1
  2013-08-31 23:52:57        -73.922600        40.755390                  1
  2013-08-31 23:54:00        -73.884468        40.737869                  1
  2013-08-31 23:54:50        -73.932846        40.796619                  1
  2013-08-31 23:57:33        -73.850494        40.722317                  1
  2013-08-31 23:58:18        -74.000633        40.732147                  2
  2013-08-31 23:58:58        -73.955841        40.804691                  2
1 2013-08-31 23:59:14        -73.964218        40.652081                  1

                       Dropoff_latitude  Trip_distance
2 2013-08-01 17:22:00              0.00            1.0
  2013-08-01 17:24:00              0.00            1.0
  2013-08-05 11:31:47              0.00            0.0
  2013-08-05 11:31:47              0.00            0.0
  2013-08-05 11:51:21              0.00            0.0
  2013-08-05 11:53:27              0.00            0.0
  2013-08-06 06:51:19              0.00            0.0
  2013-08-06 10:33:07              0.00            0.0
  2013-08-06 13:26:34              0.00            0.0
  2013-08-06 13:27:53              0.00            0.0
  2013-08-06 13:29:17              0.00            0.0
  2013-08-06 13:30:55              0.00            0.0
  2013-08-07 10:22:30              0.00            0.0
  2013-08-07 10:24:53              0.00            0.0
  2013-08-07 10:24:53              0.00            0.0
  2013-08-07 10:33:23              0.00            0.5
  2013-08-07 14:12:46              0.01            0.0
  2013-08-07 15:13:35              0.00            0.0
  2013-08-07 15:38:07              0.00            0.0
  2013-08-07 15:42:29              0.00            0.0
  2013-08-07 15:46:09              0.00            0.0
  2013-08-07 15:49:16              0.00            0.0
  2013-08-07 16:06:29              0.00            1.0
  2013-08-07 16:15:27              0.00            1.0
  2013-08-07 16:15:27              0.00            1.0
  2013-08-07 16:27:31              0.00            1.0
  2013-08-07 16:27:31              0.00            1.0
  2013-08-07 16:38:29              0.00            1.0
  2013-08-07 16:38:29              0.00            1.0
  2013-08-07 16:43:27              0.00            1.0
...                                 ...            ...
1 2013-08-31 23:23:38              2.20            0.5
2 2013-08-31 23:23:45              2.43            0.5
  2013-08-31 23:23:49              2.22            0.5
  2013-08-31 23:24:42             13.70            0.5
  2013-08-31 23:25:05              4.01            0.5
  2013-08-31 23:27:26              7.49            0.5
  2013-08-31 23:27:46              3.77            0.5
  2013-08-31 23:28:21             11.66            0.5
  2013-08-31 23:30:53             11.77            0.5
  2013-08-31 23:33:19              0.72            0.5
  2013-08-31 23:34:00              2.03            0.5
  2013-08-31 23:34:55              3.30            0.5
  2013-08-31 23:34:58              3.59            0.5
  2013-08-31 23:35:21              7.64            0.5
  2013-08-31 23:40:04              0.40            0.5
  2013-08-31 23:41:33              4.80            0.5
  2013-08-31 23:44:17              1.48            0.5
1 2013-08-31 23:45:43              0.80            0.5
2 2013-08-31 23:46:58              1.32            0.5
  2013-08-31 23:48:10              7.76            0.5
  2013-08-31 23:48:29              2.86            0.5
  2013-08-31 23:50:37              2.08            0.5
  2013-08-31 23:51:16              1.82            0.5
  2013-08-31 23:52:57              1.13            0.5
  2013-08-31 23:54:00              4.29            0.5
  2013-08-31 23:54:50              1.05            0.5
  2013-08-31 23:57:33              2.64            0.5
  2013-08-31 23:58:18              7.22            0.5
  2013-08-31 23:58:58              1.47            0.5
1 2013-08-31 23:59:14              2.20            0.5

[7095 rows x 5 columns]