In [1]:
#imports
import pandas as pd

In [2]:
#Load the csv file for green taxis into a pandas dataframe
greenAug = pd.read_csv('green_tripdata_2013-08.csv')
df_greenAug = pd.DataFrame(greenAug)

#load the csv file for NYC traffic 2012-2013 into a pandas datafram
traffic = pd.read_csv('Traffic_Volume_Counts__2012-2013_.csv')
df_traffic = pd.DataFrame(traffic)

In [3]:
#df_greenAug
#df_traffic

In [4]:
#drop rows without location data
df_greenAug= df_greenAug[df_greenAug.Pickup_longitude != 0]
#drop useless columns
df_greenAug.drop(df_greenAug.columns[[0,1,2,7,8,10,11,12,13,14,15,16,17,18,19]],axis = 1,inplace = True)

traffic_list= list(df_traffic)

#remove columns without number of traffic, definitely not the most efficient way to do this
traffic_list.remove('Segment ID')
traffic_list.remove('Roadway Name')
traffic_list.remove('From')
traffic_list.remove('To')
traffic_list.remove('Direction')
traffic_list.remove('Date')

#create a new column which is a sum of the traffic from each hour
df_traffic['24 Hour Traffic'] = df_traffic[traffic_list].sum(axis=1)
df_traffic = df_traffic.groupby('Date')
print(df_traffic)

<pandas.core.groupby.DataFrameGroupBy object at 0x000001BF13C88E10>

In [5]:
#df_greenAug

In [6]:
#rename columns because of some extra commas in the csv
df_greenAug.columns = ['Pickup_longitude','Pickup_latitude','Dropoff_latitude','Dropoff_longitude','Trip_distance']

In [7]:
df_greenAug

                       Pickup_longitude  Pickup_latitude  Dropoff_latitude  \
2 2013-08-01 17:22:00        -73.937767        40.758480        -73.937767
  2013-08-01 17:24:00        -73.937927        40.757843        -73.937927
  2013-08-05 11:31:47       -115.179100        36.137096       -115.179337
  2013-08-05 11:31:47       -115.179100        36.137096       -115.179337
  2013-08-05 11:51:21       -115.179199        36.137047       -115.179199
  2013-08-05 11:53:27       -115.179337        36.136753       -115.179276
  2013-08-06 06:51:19        -73.937721        40.758404        -73.937721
  2013-08-06 10:33:07        -76.979668        38.927082        -76.979713
  2013-08-06 13:26:34        -73.937691        40.758419        -73.937790
  2013-08-06 13:27:53        -73.937805        40.758396        -73.937775
  2013-08-06 13:29:17        -73.937744        40.758415        -73.937759
  2013-08-06 13:30:55        -73.937775        40.758366        -73.937790
  2013-08-07 10:22:30        -76.979950        38.927292        -76.979591
  2013-08-07 10:24:53        -76.979668        38.927311        -76.979889
  2013-08-07 10:24:53        -76.979668        38.927311        -76.979813
  2013-08-07 10:33:23        -76.979790        38.927311        -76.979561
  2013-08-07 14:12:46        -73.937485        40.758392        -73.937485
  2013-08-07 15:13:35       -115.179192        36.136860       -115.179283
  2013-08-07 15:38:07        -73.937485        40.758125        -73.937485
  2013-08-07 15:42:29        -73.937477        40.758175        -73.937424
  2013-08-07 15:46:09        -73.937447        40.758244        -73.937508
  2013-08-07 15:49:16        -73.937508        40.758240        -73.937447
  2013-08-07 16:06:29        -73.937424        40.758240        -73.937469
  2013-08-07 16:15:27        -73.937424        40.758167        -73.937431
  2013-08-07 16:15:27        -73.937424        40.758167        -73.937424
  2013-08-07 16:27:31        -73.937447        40.758183        -73.937492
  2013-08-07 16:27:31        -73.937447        40.758183        -73.937325
  2013-08-07 16:38:29        -73.937363        40.758148        -73.937416
  2013-08-07 16:38:29        -73.937363        40.758148        -73.937241
  2013-08-07 16:43:27        -73.937660        40.758347        -73.937729
...                                 ...              ...               ...
1 2013-08-31 23:23:38        -73.913605        40.765427        -73.918091
2 2013-08-31 23:23:45        -73.950272        40.680496        -73.934990
  2013-08-31 23:23:49        -73.844254        40.721390        -73.818474
  2013-08-31 23:24:42        -73.846169        40.754543        -73.965820
  2013-08-31 23:25:05        -73.861031        40.893051        -73.901611
  2013-08-31 23:27:26        -73.844818        40.754986        -73.969231
  2013-08-31 23:27:46        -73.954086        40.742813        -74.000793
  2013-08-31 23:28:21        -73.846001        40.754578        -73.974899
  2013-08-31 23:30:53        -73.849991        40.753479        -73.977623
  2013-08-31 23:33:19        -73.829971        40.713734        -73.824730
  2013-08-31 23:34:00        -73.845917        40.754639        -73.860458
  2013-08-31 23:34:55        -73.967758        40.693268        -73.989105
  2013-08-31 23:34:58        -73.991852        40.702530        -74.007256
  2013-08-31 23:35:21        -73.833656        40.771580        -73.843651
  2013-08-31 23:40:04        -73.926193        40.761082        -73.928421
  2013-08-31 23:41:33        -73.921158        40.743267        -73.902840
  2013-08-31 23:44:17        -73.946342        40.711445        -73.951027
1 2013-08-31 23:45:43        -73.979172        40.678406        -73.988785
2 2013-08-31 23:46:58        -73.943985        40.784100        -73.952507
  2013-08-31 23:48:10        -73.924644        40.756287        -73.984779
  2013-08-31 23:48:29        -73.920647        40.767956        -73.885201
  2013-08-31 23:50:37        -73.941200        40.805779        -73.967400
  2013-08-31 23:51:16        -73.844307        40.721352        -73.827965
  2013-08-31 23:52:57        -73.917976        40.765259        -73.922600
  2013-08-31 23:54:00        -73.845985        40.754650        -73.884468
  2013-08-31 23:54:50        -73.943115        40.785336        -73.932846
  2013-08-31 23:57:33        -73.824432        40.734287        -73.850494
  2013-08-31 23:58:18        -73.964668        40.681309        -74.000633
  2013-08-31 23:58:58        -73.932343        40.796421        -73.955841
1 2013-08-31 23:59:14        -73.980034        40.676315        -73.964218

                       Dropoff_longitude  Trip_distance
2 2013-08-01 17:22:00          40.758480           2.50
  2013-08-01 17:24:00          40.757843           2.50
  2013-08-05 11:31:47          36.136684           1.00
  2013-08-05 11:31:47          36.136684           1.20
  2013-08-05 11:51:21          36.137009           1.00
  2013-08-05 11:53:27          36.136826           1.00
  2013-08-06 06:51:19          40.758369           3.30
  2013-08-06 10:33:07          38.927326           3.25
  2013-08-06 13:26:34          40.758358           3.30
  2013-08-06 13:27:53          40.758450           3.30
  2013-08-06 13:29:17          40.758389           3.50
  2013-08-06 13:30:55          40.758350           3.30
  2013-08-07 10:22:30          38.927288           3.52
  2013-08-07 10:24:53          38.927174           3.25
  2013-08-07 10:24:53          38.927128           3.52
  2013-08-07 10:33:23          38.927151           3.52
  2013-08-07 14:12:46          40.758209           3.50
  2013-08-07 15:13:35          36.137066           1.00
  2013-08-07 15:38:07          40.758137           2.50
  2013-08-07 15:42:29          40.758152           2.50
  2013-08-07 15:46:09          40.758251           3.50
  2013-08-07 15:49:16          40.758183           2.50
  2013-08-07 16:06:29          40.758202           3.50
  2013-08-07 16:15:27          40.758213           2.50
  2013-08-07 16:15:27          40.758251           3.00
  2013-08-07 16:27:31          40.758194           2.50
  2013-08-07 16:27:31          40.758198           3.00
  2013-08-07 16:38:29          40.758087           2.50
  2013-08-07 16:38:29          40.758106           5.50
  2013-08-07 16:43:27          40.758305           2.50
...                                  ...            ...
1 2013-08-31 23:23:38          40.741680          11.00
2 2013-08-31 23:23:45          40.702396          10.50
  2013-08-31 23:23:49          40.734043           9.00
  2013-08-31 23:24:42          40.677544          39.00
  2013-08-31 23:25:05          40.876530          14.00
  2013-08-31 23:27:26          40.761219          26.00
  2013-08-31 23:27:46          40.736462          13.50
  2013-08-31 23:28:21          40.759235          38.50
  2013-08-31 23:30:53          40.779022          34.00
  2013-08-31 23:33:19          40.705601           5.50
  2013-08-31 23:34:00          40.739819           8.50
  2013-08-31 23:34:55          40.720303          14.50
  2013-08-31 23:34:58          40.733669          14.50
  2013-08-31 23:35:21          40.689556          22.50
  2013-08-31 23:40:04          40.756069           3.50
  2013-08-31 23:41:33          40.701447          17.00
  2013-08-31 23:44:17          40.724358           7.50
1 2013-08-31 23:45:43          40.670506           5.50
2 2013-08-31 23:46:58          40.773121           6.00
  2013-08-31 23:48:10          40.710838          25.00
  2013-08-31 23:48:29          40.755516          11.50
  2013-08-31 23:50:37          40.801105           9.50
  2013-08-31 23:51:16          40.710865           8.00
  2013-08-31 23:52:57          40.755390           6.00
  2013-08-31 23:54:00          40.737869          15.00
  2013-08-31 23:54:50          40.796619           5.00
  2013-08-31 23:57:33          40.722317          11.50
  2013-08-31 23:58:18          40.732147          25.50
  2013-08-31 23:58:58          40.804691           7.50
1 2013-08-31 23:59:14          40.652081           9.00

[7095 rows x 5 columns]

In [8]:
#df_greenAug['new_date'] = [d.date() for d in df_greenAug['']]
#df['new_time'] = [d.time() for d in df['my_timestamp']]

In [9]:
#df_traffic.sort_values('Date')